using AIBettingCore.Models;

namespace AIBettingAnalyst.Models;

/// <summary>
/// Represents a trading signal generated by the Analyst.
/// </summary>
public class AnalystSignal
{
    public required string MarketId { get; init; }
    public required string Strategy { get; init; } // "surebet", "scalping", "steam_move"
    public required DateTimeOffset Timestamp { get; init; }
    public double Confidence { get; init; } // 0.0 - 1.0
    public double ExpectedROI { get; init; } // Expected return on investment (percentage)
    
    // Surebet specific
    public string? BackSelectionId { get; init; }
    public string? BackSelectionName { get; init; }
    public decimal BackOdds { get; init; }
    public decimal StakeBack { get; init; }
    
    public string? LaySelectionId { get; init; }
    public string? LaySelectionName { get; init; }
    public decimal LayOdds { get; init; }
    public decimal StakeLay { get; init; }
    
    // Market context
    public decimal TotalMatched { get; init; }
    public int SecondsToStart { get; init; }
    
    // Analysis metrics
    public decimal BackWAP { get; init; }
    public decimal LayWAP { get; init; }
    public decimal Spread { get; init; }
    
    public string? Reason { get; init; } // Why this signal was generated
}

/// <summary>
/// Result of WAP (Weighted Average Price) calculation.
/// </summary>
public class WAPResult
{
    public decimal BackWAP { get; init; }
    public decimal LayWAP { get; init; }
    public decimal TotalBackSize { get; init; }
    public decimal TotalLaySize { get; init; }
    public int BackLevels { get; init; }
    public int LayLevels { get; init; }
}

/// <summary>
/// Weight of Money analysis result showing volume distribution.
/// </summary>
public class WeightOfMoneyResult
{
    public required string SelectionId { get; init; }
    public required string SelectionName { get; init; }
    public decimal TotalBackVolume { get; init; }
    public decimal TotalLayVolume { get; init; }
    public decimal NetVolume => TotalBackVolume - TotalLayVolume;
    public double BackPercentage { get; init; } // Percentage of total market back volume
    public double LayPercentage { get; init; } // Percentage of total market lay volume
}

/// <summary>
/// Surebet opportunity detected by arbitrage analysis.
/// </summary>
public class SurebetOpportunity
{
    public required string MarketId { get; init; }
    public required string BackSelectionId { get; init; }
    public required string BackSelectionName { get; init; }
    public decimal BackOdds { get; init; }
    public decimal BackSize { get; init; }
    
    public required string LaySelectionId { get; init; }
    public required string LaySelectionName { get; init; }
    public decimal LayOdds { get; init; }
    public decimal LaySize { get; init; }
    
    public double ProfitPercentage { get; init; }
    public decimal StakeBack { get; init; }
    public decimal StakeLay { get; init; }
    public decimal ExpectedProfit { get; init; }
    
    public bool IsValid => ProfitPercentage > 0 && BackSize >= StakeBack && LaySize >= StakeLay;
}
