// <auto-generated />
using System;
using AIBettingAccounting.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AIBettingAccounting.Migrations
{
    [DbContext(typeof(TradingDbContext))]
    [Migration("20260105144405_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AIBettingAccounting.Data.Entities.DailySummaryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("GrossProfit")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NetProfit")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ROI")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalCommission")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalTrades")
                        .HasColumnType("integer");

                    b.Property<int>("WinningTrades")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("daily_summaries", (string)null);
                });

            modelBuilder.Entity("AIBettingAccounting.Data.Entities.TradeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Commission")
                        .HasColumnType("numeric")
                        .HasColumnName("commission");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("MarketId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("market_id");

                    b.Property<decimal?>("NetProfit")
                        .HasColumnType("numeric")
                        .HasColumnName("net_profit");

                    b.Property<decimal>("Odds")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ProfitLoss")
                        .HasColumnType("numeric")
                        .HasColumnName("profit_loss");

                    b.Property<string>("SelectionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("selection_id");

                    b.Property<decimal>("Stake")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("MarketId");

                    b.HasIndex("Status");

                    b.HasIndex("Timestamp");

                    b.ToTable("trades", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
